Important fundamentals regarding to TensorFlow

##Intoduction to Tensors

In [ ]:
import tensorflow as tf
print(tf.__version__)

2.17.1


##Creating Tensors with tf.constant()

In [ ]:
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
scalar.ndim

0

##Create a vector

In [ ]:
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
vector.ndim

1

In [ ]:
matrix = tf.constant([[10,7],[7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
matrix.ndim

2

 ##Create another matrix

In [ ]:
another_matrix = tf.constant([[10.,7.],[3.,2.],[8.,9.]], dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

#Let's create a tensor

In [ ]:
tensor = tf.constant([[[1,2,3],[4,5,6]],
                     [[1,4,5],[3,4,5]],
                     [[2,3,4],[3,5,3]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 4, 5],
        [3, 4, 5]],

       [[2, 3, 4],
        [3, 5, 3]]], dtype=int32)>

In [ ]:
tensor.ndim

3

##Create Tensors with tf.variable()
###Changable Tensor
---



In [ ]:
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
changeable_tensor = tf.Variable([10,5])
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  5], dtype=int32)>

In [ ]:
#changeable_tensor[0] = 7
#Error

In [ ]:
changeable_tensor[0].assign(5)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([5, 5], dtype=int32)>

In [ ]:
unchangeable_tensor = tf.constant([3,4])
unchangeable_tensor

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 4], dtype=int32)>

In [ ]:
#unchangeable_tensor[0].assign(5)
#unchangeable_tensor
#Error

##Creating Random Tensors

##Create two random sensors

In [ ]:
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(3,2))
random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193765, -1.8107855 ]], dtype=float32)>

In [ ]:

]
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))
random_2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193765, -1.8107855 ]], dtype=float32)>

##Shuffling orders of tensors (When shuffling data)

In [ ]:
not_shuffled = tf.constant([[10,7],[2,5],[5,8]])
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 2,  5],
       [ 5,  8]], dtype=int32)>

In [ ]:
not_shuffled.ndim

2

In [ ]:
tf.random.shuffle(not_shuffled)
#Shuffled across first dimension
#Everytime we run, different order

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 5,  8],
       [ 2,  5],
       [10,  7]], dtype=int32)>

In [ ]:
tf.random.shuffle(not_shuffled, seed=42) #operationlevelSeed
#Still shuffling

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 5,  8],
       [ 2,  5],
       [10,  7]], dtype=int32)>

In [ ]:
tf.random.set_seed(42) #GloballevelSeed
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 2,  5],
       [ 5,  8]], dtype=int32)>

##Creating Tensors using Numpy

In [ ]:
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [ ]:
tf.zeros(shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

##Turning Numpy arrays to Tensors
Main difference in between tensors and numpy is tensors can be run on GPU much faster

In [ ]:
import numpy as np
numpy_A = np.arange(1,25, dtype = np.int32)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
A = tf.constant(numpy_A)
A

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>

In [ ]:
AB = tf.constant(numpy_A, shape =(2,3,4))
AB,A
# 2*3*4 = 12

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

##Getting Information from Tensors


*   Shape -> no.of elements of each dimension of a tensor.
*   Axis -> A particular dimension of a tensor
*   Rank -> No.of tensor dimensions
*   Size -> Total no.of elements in a tensor









In [ ]:
rank_4_tensor = tf.zeros([2,3,4,5])
rank_4_tensor

In [ ]:
rank_4_tensor[0]

In [ ]:
rank_4_tensor.ndim, rank_4_tensor.shape, tf.size(rank_4_tensor)

In [ ]:
2*3*4*5


##Get variable attributes of tensor

In [ ]:
print("Datatype of every element:", rank_4_tensor.dtype)
print("Number of dimensions (rank):", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along axis 0 of tensor:", rank_4_tensor.shape[0])
print("Elements along last axis of tensor:", rank_4_tensor.shape[-1])
print("Total number of elements (2*3*4*5):", tf.size(rank_4_tensor).numpy()) # .numpy() converts to NumPy array

##Indexing Tensors

In [ ]:
#Get First Two elements of first two elements
rank_4_tensor[:2,:2,:2,:2]

In [ ]:
#Get Frist Element from Each Dimension from each index except final
rank_4_tensor[:1,:1,:,:1]

In [ ]:
rank_4_tensor.shape

In [ ]:
rank_2_tensor = tf.constant(([[10,7],[4,5]]))

In [ ]:
rank_2_tensor.shape, rank_2_tensor.ndim

In [ ]:
tf.expand_dims(rank_2_tensor, axis=-1) # "-1" means last axis


##Manipulating Tensors with Basic Operations

In [ ]:
tensor = tf.constant([[10,7],[3,4]])
tensor

In [ ]:
tensor + 10

In [ ]:
tf.multiply(tensor,10)

##Matrix Multiplication

In [ ]:
print(tensor)

In [ ]:
tf.matmul(  tensor, tensor)

In [ ]:
tensor * tensor

In [ ]:
tensor1 = tf.constant([[1,2,5],
                        [7,2,1],
                        [3,3,3]])
tensor2 = tf.constant([[3,5],
                       [6,7],
                       [1,8]])
tf.matmul(tensor1, tensor2)

##Matrix multiplication with Python @

In [ ]:
tensor @ tensor

In [ ]:
tensor * tensor

###Resource : https://www.mathsisfun.com/algebra/matrix-multiplying.html
Two rules for Matrix Multiplication
*   The inner dimensions should match
*   The resulting matrix has the shape of inner dimension



In [ ]:
X = tf.constant([[2,3],
                 [3,4],
                 [3,6]])
Y = tf.constant([[2,5],
                 [5,7],
                 [3,9]])
# X @ Y  -> Error Because not compatible

##Let's change shape of Y

In [ ]:
Y1 = tf.reshape(Y, shape=(2,3))

In [ ]:
X @ Y1

In [ ]:
tf.matmul(X,Y1)

##Can do this with Transpose
Not the difference in between transpose and reshape




In [ ]:
X , tf.transpose(X), tf.reshape(X, shape=(2,3))

In [ ]:
Y2 = tf.transpose(Y)

In [ ]:
X @ Y2

##Dot Product/ Matrix Multiplication
###Transpose is better than reshape
###tf.matmul()
###tf.tensordot()  for this axes is important parameter

In [ ]:
#Perform X @ Y ; Have to transpose Y
X , Y

In [ ]:
tf.tensordot(X, tf.transpose(Y),axes=1)
#axes is important. if neglected error;

In [ ]:
tf.tensordot(X,tf.reshape(Y, shape=(2,3)), axes=1)

In [ ]:
Y , tf.reshape(Y, shape=(2,3)), tf.transpose(Y)

##Changing the Data Types of Tensors

In [ ]:
B = tf.constant([[1.3,5.4],
                 [2.5,4.5]])
B.dtype

In [ ]:
C = tf.constant([[10,7],[3,4]])
C.dtype

### 32 bit precision tensor Vs 16 bit precision tensor
16bit use less memory and fast

In [ ]:
B = tf.cast(B,dtype = tf.float16)

In [ ]:
B , B.dtype

(<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
 array([[1.3, 5.4],
        [2.5, 4.5]], dtype=float16)>,
 tf.float16)

In [ ]:
C = tf.cast(C, dtype = tf.float16)
C, C.dtype

(<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
 array([[10.,  7.],
        [ 3.,  4.]], dtype=float16)>,
 tf.float16)

##Tensor Aggregation
Aggregating sensors = condensing then from multiple values down to a smaller amount of value

In [ ]:
#Get the absoulte Value
D = tf.constant([-7,-10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [ ]:
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

##Forms of Aggregation
*   Get Maximun
*   Get Minimum
*   Get Mean of a tensor
*   Get sum of a tensor




In [ ]:
E = tf.constant(np.random.randint(0,100,size=50))

In [ ]:
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([81, 95, 90, 14, 59, 21, 38, 83, 94, 87, 21, 28, 20, 69,  4, 45, 64,
       36,  8, 11, 21, 16, 53, 89, 90,  8,  9, 67, 67, 61, 25, 38, 58, 30,
       34, 42, 54, 92, 15, 77, 20, 88, 20, 64, 87, 84, 79, 97,  1, 65])>

In [ ]:
tf.size(E), E.shape, E.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [ ]:
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=1>

In [ ]:
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=97>

In [ ]:
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=50>

In [ ]:
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2519>

In [ ]:
##To find variance, we need tensorflow probabilities'
import tensorflow_probability as tfp
tfp.stats.variance(E)

<tf.Tensor: shape=(), dtype=int64, numpy=918>

In [ ]:
tf.math.reduce_std(tf.cast(E , dtype =tf.float32))
tf.math.reduce_variance(tf.cast(E , dtype =tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=918.7556>

##Find Positional Max and Min

In [ ]:
tf.random.set_seed(42)
tensor_new = tf.random.uniform(shape=[50])
tensor_new

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [ ]:
tf.argmax(tensor_new)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [ ]:
tensor_new[tf.argmax(tensor_new)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [ ]:
tensor_new[tf.argmax(tensor_new)] == tf.reduce_max(tensor_new)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

##Squeezing Sensors / Removing all 1-dimension axes

In [ ]:
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape=[50]), shape=(1,1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [ ]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [ ]:
G_squeezed = tf.squeeze(G)
G_squeezed, G_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>,
 TensorShape([50]))

##One Hot Encoding

In [ ]:
some_list =[0,1,2,3]
tf.one_hot(some_list, depth=4)
#depth is important

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [ ]:
#Specift custome values
tf.one_hot(some_list, depth=4, on_value="Yo I love Deep Learning", off_value="I also like to dance")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'Yo I love Deep Learning', b'I also like to dance',
        b'I also like to dance', b'I also like to dance'],
       [b'I also like to dance', b'Yo I love Deep Learning',
        b'I also like to dance', b'I also like to dance'],
       [b'I also like to dance', b'I also like to dance',
        b'Yo I love Deep Learning', b'I also like to dance'],
       [b'I also like to dance', b'I also like to dance',
        b'I also like to dance', b'Yo I love Deep Learning']],
      dtype=object)>

##Trying more Tensor Operations
Square,log

In [ ]:
H = tf.range(1,10)

In [ ]:
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [ ]:
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [ ]:
tf.sqrt(tf.cast(H, dtype=tf.float32))
#if int, there will be error

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.2360678, 2.4494896,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [ ]:
tf.math.log(tf.cast(H, dtype = tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

##Numpy Tensor Compatibility